# Generated by Django 4.2.29 on 2026-03-04 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'managed': False, 'verbose_name_plural': 'Autores'},
        ),
    ]
