# Generated by Django 4.2.29 on 2026-03-04 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0002_alter_autor_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Autor',
        ),
        migrations.DeleteModel(
            name='Libro',
        ),
        migrations.DeleteModel(
            name='Prestamo',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
